Repository delta-reporter/delta-frontend, pull requests merged in 2020-09, with the labels that each got.

#45 Adding a flaky badge
  components/MuiTheme.ts
  components/templates/BasePage.tsx
  components/templates/ListOfSuites.tsx
  components/templates/Test.tsx
  package-lock.json
  package.json
  pages/index.tsx
  pages/launches/[launchesByProjectId].tsx
  pages/testruns/[runsByLaunchId].tsx
  pages/tests/[testsByRunId].tsx
Labels: New Feature:champagne:

#42 Realtime notifications for launches and projects
  .eslintrc.json
  components/templates/eventNotification.tsx
  components/templates/index.ts
  hooks/useSocket.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  pages/launches/[launchesByProjectId].tsx
  public/favicon.ico
  tests/end_to_end/package-lock.json
  tests/end_to_end/package.json
Labels: New Feature:champagne:, dependencies

#48 Removing Redux and implementing server side props
  pages/_app.tsx
  pages/_document.tsx
  pages/_error.tsx
  pages/api/input.tsx
  pages/index.tsx
  pages/launches/[launchesByProjectId].tsx
  store/api/InputApi.ts
  store/api/index.ts
  store/configureStore.development.ts
  store/configureStore.production.ts
  store/configureStore.ts
  store/counter/actions.ts
  store/counter/index.ts
  store/counter/reducers.ts
  store/counter/selectors.ts
  store/counter/states.ts
  store/page/actions.ts
  store/page/index.ts
  store/page/reducers.ts
  store/page/selectors.ts
  store/page/states.ts
  store/reducers.ts
  store/redux-saga/actions.ts
  store/redux-saga/index.ts
  store/redux-saga/reducers.ts
  store/redux-saga/sagas.ts
  store/redux-saga/selectors.ts
  store/redux-saga/states.ts
  store/sagas.ts
  store/states.ts
  tests/end_to_end/src/wdio/home.page.ts
Labels: Bug Fix :bug:, Config change :construction:, Refactoring :nerd_face:

#50 Realtime resolution update
  components/templates/ListOfSuites.tsx
  components/templates/ListOfTests.tsx
  components/templates/Test.tsx
  components/templates/TestResolution.tsx
  components/templates/index.ts
  pages/index.tsx
Labels: New Feature:champagne:, Refactoring :nerd_face:
