Repository delta-reporter/delta-frontend, pull requests merged in 2020-06, with the labels that each got.

#10 Set test resolution, fixing stats position
  components/templates/SuitesAndTestsList.tsx
  components/templates/TestInfoSection.tsx
  components/templates/index.ts
  components/templates/showStatusIcon.js
  components/templates/showTestStats.js
  pages/failedTests/[failedTestsByRunId].tsx
  pages/index.tsx
  pages/launches/[launchesByProjectId].tsx
  pages/testruns/[runsByLaunchId].tsx
  pages/tests/[testsByRunId].tsx
Labels: Bug Fix :bug:, Refactoring :nerd_face:

#12 Finish launch + new fonts
  components/templates/BasePage.tsx
  components/templates/SuitesAndTestsList.tsx
  components/templates/TestExpanded.tsx
  components/templates/TestsList.tsx
  components/templates/showStatusIcon.js
  components/templates/showTestStats.js
  pages/failedTests/[failedTestsByRunId].tsx
  pages/launches/[launchesByProjectId].tsx
  pages/tests/[testsByRunId].tsx
Labels: Design change :high_heel:, New Feature:champagne:

#15 Fixing broken build on heroku
  pages/launches/[launchesByProjectId].tsx
Labels: Bug Fix :bug:

#13 Added preliminary version of media tab for tests
  components/templates/TestExpanded.tsx
Labels: New Feature:champagne:, help wanted

#14 Adding publicDeltaCore env var
  components/templates/TestExpanded.tsx
  next.config.js
  pages/launches/[launchesByProjectId].tsx
  serverless.yml
Labels: Config change :construction:

#17 New style for tests - splitting page in half
  components/templates/BasePage.tsx
  components/templates/TestExpanded.tsx
  components/templates/showTestStats.js
  pages/tests/[testsByRunId].tsx
Labels: Design change :high_heel:

#18 Bringing the same design to failedTests page
  components/templates/TestExpanded.tsx
  pages/failedTests/[failedTestsByRunId].tsx
  pages/index.tsx
  pages/tests/[testsByRunId].tsx
Labels: Design change :high_heel:

#20 Media bug fix + style
  components/templates/TestExpanded.tsx
  components/templates/TestExpansionPanel.tsx
  components/templates/TestResolution.tsx
  components/templates/index.ts
  package-lock.json
  package.json
  pages/tests/[testsByRunId].tsx
Labels: Bug Fix :bug:, Refactoring :nerd_face:

#21 Foundation for end to end tests
  azure-pipelines.yml
  tests/end_to_end/.eslintrc.js
  tests/end_to_end/.gitignore
  tests/end_to_end/config/base.conf.ts
  tests/end_to_end/config/chromedriver.conf.js
  tests/end_to_end/config/chromedriver.conf.ts
  tests/end_to_end/package-lock.json
  tests/end_to_end/package.json
  tests/end_to_end/src/base.page.ts
  tests/end_to_end/src/wdio/home.page.ts
  tests/end_to_end/test/specs/webdriver/core.ts
  tests/end_to_end/tsconfig.json
  tests/end_to_end/types/wdio.d.ts
  tsconfig.json
Labels: New Feature:champagne:
