Repository delta-reporter/delta-frontend, pull requests merged in 2020-07, with the labels that each got.

#24 Delta View - Pyramid Rose chart view for test launches
  azure-pipelines.yml
  components/templates/TestExpanded.tsx
  package-lock.json
  package.json
  pages/launches/[launchesByProjectId].tsx
Labels: Design change :high_heel:, New Feature:champagne:

#23 Creating charts page (not in use for now) + showing resolution
  components/templates/BasePage.tsx
  components/templates/Sidebar.tsx
  components/templates/SuitesAndTestsList.tsx
  components/templates/TestExpanded.tsx
  components/templates/TestExpansionPanel.tsx
  components/templates/TestResolution.tsx
  components/templates/TestsList.tsx
  components/templates/index.ts
  components/templates/showStatusIcon.js
  package-lock.json
  package.json
  pages/charts.tsx
  pages/failedTests/[failedTestsByRunId].tsx
  pages/index.tsx
  pages/launches/[launchesByProjectId].tsx
  pages/testruns/[runsByLaunchId].tsx
  pages/tests/[testsByRunId].tsx
Labels: Design change :high_heel:, New Feature:champagne:

#26 Historical tests
  components/templates/SpacingPaper.tsx
  components/templates/Test.tsx
  components/templates/TestExpandablePanels.tsx
  components/templates/TestHistory.tsx
  components/templates/index.ts
  components/templates/showDate.js
  components/templates/showResolution.js
  components/templates/showStatusIcon.js
  package-lock.json
  package.json
Labels: New Feature:champagne:

#29 moving deltaView to a component, showing selected page for launch
  components/templates/BasePage.tsx
  components/templates/DeltaViewForLaunches.tsx
  components/templates/ListOfSuites.tsx
  components/templates/Pagination.tsx
  components/templates/Test.tsx
  components/templates/TestHistory.tsx
  components/templates/index.ts
  components/templates/showAndChangeLaunchStatus.tsx
  components/templates/showDate.js
  components/templates/showResolution.js
  components/templates/showStatusIcon.js
  package-lock.json
  package.json
  pages/charts.tsx
  pages/launches/[launchesByProjectId].tsx
  pages/tests/[testsByRunId].tsx
  tests/end_to_end/test/specs/webdriver/core.ts
Labels: Design change :high_heel:, Refactoring :nerd_face:

#30 Filter by status
  components/templates/DeltaViewForLaunches.tsx
  components/templates/ListOfSuites.tsx
  components/templates/Test.tsx
  components/templates/TestExpandablePanels.tsx
  components/templates/TestHistory.tsx
  components/templates/showStatusIcon.js
  components/templates/showTestStats.js
  package-lock.json
  package.json
  pages/launches/[launchesByProjectId].tsx
  pages/tests/[testsByRunId].tsx
  pages/tests/failedTests/[failedTestsByRunId].tsx
  pages/tests/passedTests/[passedTestsByRunId].tsx
  pages/tests/skippedTests/[skippedTestsByRunId].tsx
  tests/end_to_end/test/specs/webdriver/core.ts
Labels: New Feature:champagne:
